# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1270b2a69f287a17bea02d6813cbe5cb0ae8e8f7ba66b4bb656dc4b8bf1d3554c66206ea78a5b46afbc4f6d9960595fe7b524a5ce3668e287bc9fe8b45c0ad9c

test:
  secret_key_base: 664088f8ea59be606de390fda3c4f86a0a516f7fa8272f180c3c905568b7ce244938e88c3822a85638bd22a4297eb26bc44492d618a40c30f84a77dabb251a3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
